services:
  base:
    build:
      target: base
    stdin_open: true
    tty: true

  build:
    build:
      target: build

  dev:
    command: bash
    build:
      target: dev
    privileged: True
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/MicrasFirmware:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
