###############################################################################
## Toolchain Configuration
###############################################################################

set(CMAKE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cube")
include(cube/cmake/gcc-arm-none-eabi.cmake)
set(CMAKE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

# The toolchain file is regenerated by STM32CubeMX, so its single hardcoded map file name, which
# every target would overwrite, is removed here instead of there
string(REGEX REPLACE " *-Wl,-Map=[^ ]*" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")

# Debug information is kept in every configuration, since it never reaches the target and is what
# makes a crash from a competition run symbolisable. Release optimises for speed rather than size:
# the image uses a small fraction of the 1 MiB flash. -fno-math-errno is what turns sqrtf and
# hypotf into FPU instructions, and -ffp-contract=fast fuses multiply-adds into VFMA.
#
# -ffast-math is deliberately absent: the controllers rely on well defined behaviour around zero,
# and a stray NaN becoming undefined behaviour is the worst possible failure mode for a robot.
set(MICRAS_MATH_FLAGS "-fno-math-errno -ffp-contract=fast")

set(CMAKE_C_FLAGS_DEBUG     "-Og -g3")
set(CMAKE_CXX_FLAGS_DEBUG   "-Og -g3")
set(CMAKE_C_FLAGS_RELEASE   "-O2 -g3 -flto ${MICRAS_MATH_FLAGS}")
set(CMAKE_CXX_FLAGS_RELEASE "-O2 -g3 -flto ${MICRAS_MATH_FLAGS}")
set(CMAKE_C_FLAGS_RELWITHDEBINFO     "-O2 -g3 ${MICRAS_MATH_FLAGS}")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO   "-O2 -g3 ${MICRAS_MATH_FLAGS}")
set(CMAKE_C_FLAGS_MINSIZEREL   "-Os -g3 -flto ${MICRAS_MATH_FLAGS}")
set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -g3 -flto ${MICRAS_MATH_FLAGS}")

# -flto only takes effect when the link step carries the same optimisation level as the compile step
set(CMAKE_EXE_LINKER_FLAGS_RELEASE     "-O2 -flto")
set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL  "-Os -flto")
