###############################################################################
## Toolchain Configuration
###############################################################################

set(CMAKE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cube")
include(cube/cmake/gcc-arm-none-eabi.cmake)
set(CMAKE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

# The toolchain file hardcodes one map file name that every target would overwrite, and it is
# regenerated by STM32CubeMX, so the flag is stripped here rather than edited there
string(REGEX REPLACE " *-Wl,-Map=[^ ]*" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")

# Debug information costs no flash, since it never reaches the target, and makes a crash from a
# competition run symbolizable. Release optimizes for speed rather than size, because the image
# uses a small fraction of the 1 MiB flash: -fno-math-errno turns sqrtf and hypotf into FPU
# instructions, and -ffp-contract=fast fuses multiply-adds into VFMA. -ffast-math is deliberately
# absent, since the controllers rely on well defined behavior around zero.
set(MICRAS_MATH_FLAGS "-fno-math-errno -ffp-contract=fast")

set(CMAKE_C_FLAGS_DEBUG     "-Og -g3")
set(CMAKE_CXX_FLAGS_DEBUG   "-Og -g3")
set(CMAKE_C_FLAGS_RELEASE   "-O2 -g3 ${MICRAS_MATH_FLAGS}")
set(CMAKE_CXX_FLAGS_RELEASE "-O2 -g3 ${MICRAS_MATH_FLAGS}")
set(CMAKE_C_FLAGS_RELWITHDEBINFO     "-O2 -g3 ${MICRAS_MATH_FLAGS}")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO   "-O2 -g3 ${MICRAS_MATH_FLAGS}")
set(CMAKE_C_FLAGS_MINSIZEREL   "-Os -g3 ${MICRAS_MATH_FLAGS}")
set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -g3 ${MICRAS_MATH_FLAGS}")

# Asking for link time optimization through the property, rather than putting -flto in the flags
# above, is what makes CMake archive with gcc-ar and gcc-ranlib. Plain ar cannot read a bytecode
# object and writes a symbol index without any of its symbols, which the link cannot then resolve.
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE    TRUE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL TRUE)

# The bytecode is finally compiled at link time, so the optimization level belongs here too
set(CMAKE_EXE_LINKER_FLAGS_RELEASE     "-O2")
set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL  "-Os")
