###############################################################################
## Project Warning Flags
###############################################################################

# These flags deliberately live here and not in cube/cmake/gcc-arm-none-eabi.cmake,
# because that file is regenerated by STM32CubeMX and any edit to it is lost.
# The target is linked privately into the micras_* libraries and the executables, so that
# the Cube sources are never compiled with it.

option(MICRAS_WERROR "Treat compiler warnings as errors" OFF)

add_library(micras_warnings INTERFACE)
add_library(micras::warnings ALIAS micras_warnings)

# The -Wduplicated-* and -Wuseless-cast flags are GCC only
target_compile_options(micras_warnings INTERFACE
    -Wall
    -Wextra
    -Wpedantic
    -Wcast-align
    -Wcast-qual
    -Wdouble-promotion
    -Wduplicated-branches
    -Wduplicated-cond
    -Wfloat-conversion
    -Wformat=2
    -Wimplicit-fallthrough
    -Wmisleading-indentation
    -Wnull-dereference
    -Wsign-conversion
    -Wundef
    -Wunused-parameter
    -fno-common
    $<$<BOOL:${MICRAS_WERROR}>:-Werror>

    # C++ only, they make the C compiler warn about the command line itself
    $<$<COMPILE_LANGUAGE:CXX>:-Wnon-virtual-dtor>
    $<$<COMPILE_LANGUAGE:CXX>:-Wold-style-cast>
    $<$<COMPILE_LANGUAGE:CXX>:-Woverloaded-virtual>
    $<$<COMPILE_LANGUAGE:CXX>:-Wuseless-cast>
)
