###############################################################################
## Project Warning Flags
###############################################################################

# These flags deliberately live here and not in cube/cmake/gcc-arm-none-eabi.cmake,
# because that file is regenerated by STM32CubeMX and any edit to it is lost.

option(MICRAS_WERROR "Treat compiler warnings as errors" OFF)

# The -Wduplicated-* and -Wuseless-cast flags are GCC only
set(MICRAS_WARNING_OPTIONS
    -Wall
    -Wextra
    -Wpedantic
    -Wcast-align
    -Wcast-qual
    -Wdouble-promotion
    -Wduplicated-branches
    -Wduplicated-cond
    -Wfloat-conversion
    -Wformat=2
    -Wimplicit-fallthrough
    -Wmisleading-indentation
    -Wnull-dereference
    -Wsign-conversion
    -Wundef
    -Wunused-parameter
    -fno-common
    $<$<BOOL:${MICRAS_WERROR}>:-Werror>

    # C++ only, they make the C compiler warn about the command line itself
    $<$<COMPILE_LANGUAGE:CXX>:-Wnon-virtual-dtor>
    $<$<COMPILE_LANGUAGE:CXX>:-Wold-style-cast>
    $<$<COMPILE_LANGUAGE:CXX>:-Woverloaded-virtual>
    $<$<COMPILE_LANGUAGE:CXX>:-Wuseless-cast>
)

# Applied per target rather than through CMAKE_CXX_FLAGS, so that the generated sources are never
# compiled with them, and as options rather than through a target, so that no package ends up
# carrying a build policy of ours in its interface
function(micras_apply_warnings)
    foreach(TARGET_NAME ${ARGN})
        target_compile_options(${TARGET_NAME} PRIVATE ${MICRAS_WARNING_OPTIONS})
    endforeach()
endfunction()
