name: Add binaries to release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v7

      - name: 🐋 Build Docker image
        run: docker build --file .docker/Dockerfile --target build --tag micras:build .

      - name: 🔨 Build project
        run: |
          docker run --name release micras:build make -C build --no-print-directory -j
          docker cp release:/project/build/ output/

      - name: ⬆️ Upload binaries
        run: gh release upload "${{ github.event.release.tag_name }}" output/*.hex output/*.elf --clobber
        env:
          GH_TOKEN: ${{ github.token }}
