name: Add binaries to release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: 🐋 Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .docker/Dockerfile
          target: build
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache-filters: build
          tags: micras:build

      - name: 🔨 Build project
        run: |
          docker run --name release micras:build make -C build --no-print-directory -j
          docker cp release:/project/build/ output/

      - name: ⬆️ Upload binaries
        run: gh release upload "${{ github.event.release.tag_name }}" output/*.hex output/*.elf --clobber
        env:
          GH_TOKEN: ${{ github.token }}
